apiVersion: v1
kind: Pod
metadata:
  name: mfcp-example-proxy-gcsfuse
  namespace: csi-dev
spec:
  terminationGracePeriodSeconds: 10
  initContainers:
  - name: starter
    image: ghcr.io/pfnet-research/meta-fuse-csi-plugin/mfcp-example-proxy-gcsfuse:latest
    imagePullPolicy: IfNotPresent
    command: ["gcsfuse"]
    args: ["--uid=0", "--gid=0", "--temp-dir=/gcsfuse-temp", "--implicit-dirs", "--foreground", "--log-file=/dev/fd/1", "--log-format=text", "mnaoki-csi-dev", "/tmp"]
    env:
    - name: FUSERMOUNT3PROXY_FDPASSING_SOCKPATH
      value: "/fusermount3-proxy/fuse-csi-ephemeral.sock"
    volumeMounts:
    - name: fuse-fd-passing
      mountPath: /fusermount3-proxy
    - name: gcsfuse-temp
      mountPath: /gcsfuse-temp
    - name: fuse-csi-ephemeral
      mountPath: /data
      readOnly: true
      mountPropagation: HostToContainer
    startupProbe:
      exec:
        command: ['sh', '-c', 'mount | grep /data | grep fuse']
      failureThreshold: 300
      periodSeconds: 1
  containers:
  - image: busybox
    name: busybox
    command: ["sleep"]
    args: ["infinity"]
    volumeMounts:
    - name: fuse-csi-ephemeral
      mountPath: /data
      readOnly: true
      mountPropagation: HostToContainer
    - name: fuse-csi-ephemeral
      mountPath: /data-subpath
      readOnly: true
      subPath: subdir
      mountPropagation: HostToContainer
  serviceAccountName: csi-dev-ksa
  volumes:
  - name: fuse-fd-passing
    emptyDir: {}
  - name: gcsfuse-temp
    emptyDir: {}
  - name: fuse-csi-ephemeral
    csi:
      driver: meta-fuse-csi-plugin.csi.storage.pfn.io
      readOnly: true
      volumeAttributes:
        fdPassingEmptyDirName: fuse-fd-passing
        fdPassingSocketName: fuse-csi-ephemeral.sock
