name: "E2E test with kind"

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  e2e-with-kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
        # buildkit requires $ACTIONS_CACHE_URL and $ACTIONS_RUNTIME_TOKEN for GHA build cache
      - name: e2e-test
        run: |
          make test-e2e
